const ADD_TO_DO = 'ADD_TO_DO'
const DELETE_TO_DO = 'DELETE_TODO'
const TOOGLE_TO_DO = 'TOOGLE_TO_DO'
const SET_VISILIBILITY = 'SET_VISIBILITY'
export {ADD_TO_DO,DELETE_TO_DO,TOOGLE_TO_DO,SET_VISILIBILITY}